;;;; scripts/generate-c-source.lisp — build-time C code generator for SMC
;;;;
;;;; Usage:
;;;;   sbcl --script scripts/generate-c-source.lisp <output-file>
;;;;
;;;; This script loads the SMC system, warms up the cache on a small set of
;;;; representative expressions, and emits a C source file containing a
;;;; dispatch table for those expressions. The generated file is intended to
;;;; be compiled into a host program for the production hot path.
;;;;
;;;; In Milestone 1 the generator is intentionally simple: it emits a small
;;;; set of hard-coded expressions as a proof of concept. Milestone 2 will
;;;; replace this with a full cache walker that assigns stable IDs to all hot
;;;; cached expressions.

(require :asdf)

(pushnew *default-pathname-defaults* asdf:*central-registry*)

(asdf:load-system :self-modifying-calculator)

(defun generate-c-source (output-path)
  "Generate a C source file at OUTPUT-PATH containing cached expressions."
  ;; Warm up the cache with a few representative scalar expressions.
  (let ((exprs '("2+3*4"
                 "(2+3)*4"
                 "2^3^2"
                 "10-4/2"
                 "1.5*2"
                 "7/2")))
    (dolist (expr exprs)
      (smc:run-calculator expr)))

  ;; Emit the generated C file.
  (ensure-directories-exist output-path)
  (with-open-file (stream output-path
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create)
    (format stream "/* smc_generated.c — generated by SMC build-time optimizer */~%")
    (format stream "/* This file is machine-generated. Do not hand-edit. */~%~%")
    (format stream "#include \"smc.h\"~%")
    (format stream "#include <math.h>~%~%")

    ;; Stable expression IDs.
    (format stream "/* Stable expression IDs */~%")
    (format stream "#define SMC_EXPR_2_PLUS_3_TIMES_4   1~%")
    (format stream "#define SMC_EXPR_PAREN_2_PLUS_3_TIMES_4 2~%")
    (format stream "#define SMC_EXPR_2_POW_3_POW_2    3~%")
    (format stream "#define SMC_EXPR_10_MINUS_4_DIV_2 4~%")
    (format stream "#define SMC_EXPR_1_5_TIMES_2      5~%")
    (format stream "#define SMC_EXPR_7_DIV_2         6~%")
    (format stream "#define SMC_EXPR_COUNT           6~%~%")

    ;; Named wrappers for direct calls.
    (format stream "/* Named wrappers for direct calls */~%")
    (format stream "int smc_expr_2_plus_3_times_4(double *out) {~%")
    (format stream "    *out = 2.0 + 3.0 * 4.0;~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    (format stream "int smc_expr_paren_2_plus_3_times_4(double *out) {~%")
    (format stream "    *out = (2.0 + 3.0) * 4.0;~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    (format stream "int smc_expr_2_pow_3_pow_2(double *out) {~%")
    (format stream "    *out = pow(2.0, pow(3.0, 2.0));~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    (format stream "int smc_expr_10_minus_4_div_2(double *out) {~%")
    (format stream "    *out = 10.0 - 4.0 / 2.0;~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    (format stream "int smc_expr_1_5_times_2(double *out) {~%")
    (format stream "    *out = 1.5 * 2.0;~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    (format stream "int smc_expr_7_div_2(double *out) {~%")
    (format stream "    *out = 7.0 / 2.0;~%")
    (format stream "    return SMC_OK;~%")
    (format stream "}~%~%")

    ;; Generic dispatch by ID.
    (format stream "/* Generic dispatch by stable expression ID */~%")
    (format stream "int smc_call_double(smc_expr_id_t expr_id,~%")
    (format stream "                    const double *args, size_t argc,~%")
    (format stream "                    double *out) {~%")
    (format stream "    (void)args;~%")
    (format stream "    (void)argc;~%")
    (format stream "    switch (expr_id) {~%")
    (format stream "        case SMC_EXPR_2_PLUS_3_TIMES_4:   return smc_expr_2_plus_3_times_4(out);~%")
    (format stream "        case SMC_EXPR_PAREN_2_PLUS_3_TIMES_4: return smc_expr_paren_2_plus_3_times_4(out);~%")
    (format stream "        case SMC_EXPR_2_POW_3_POW_2:    return smc_expr_2_pow_3_pow_2(out);~%")
    (format stream "        case SMC_EXPR_10_MINUS_4_DIV_2: return smc_expr_10_minus_4_div_2(out);~%")
    (format stream "        case SMC_EXPR_1_5_TIMES_2:      return smc_expr_1_5_times_2(out);~%")
    (format stream "        case SMC_EXPR_7_DIV_2:         return smc_expr_7_div_2(out);~%")
    (format stream "        default: return SMC_ERR_INVALID;~%")
    (format stream "    }~%")
    (format stream "}~%~%")

    ;; Metadata helpers.
    (format stream "int smc_expr_count(void) {~%")
    (format stream "    return SMC_EXPR_COUNT;~%")
    (format stream "}~%~%")

    (format stream "size_t smc_expr_arity(smc_expr_id_t id) {~%")
    (format stream "    (void)id;~%")
    (format stream "    return 0;  /* all generated expressions are ground */~%")
    (format stream "}~%~%")

    (format stream "const char *smc_expr_source(smc_expr_id_t id) {~%")
    (format stream "    switch (id) {~%")
    (format stream "        case SMC_EXPR_2_PLUS_3_TIMES_4:   return \"2+3*4\";~%")
    (format stream "        case SMC_EXPR_PAREN_2_PLUS_3_TIMES_4: return \"(2+3)*4\";~%")
    (format stream "        case SMC_EXPR_2_POW_3_POW_2:    return \"2^3^2\";~%")
    (format stream "        case SMC_EXPR_10_MINUS_4_DIV_2: return \"10-4/2\";~%")
    (format stream "        case SMC_EXPR_1_5_TIMES_2:      return \"1.5*2\";~%")
    (format stream "        case SMC_EXPR_7_DIV_2:         return \"7/2\";~%")
    (format stream "        default: return NULL;~%")
    (format stream "    }~%")
    (format stream "}~%"))
  output-path)

(defun main ()
  (let ((args (cdr sb-ext:*posix-argv*)))
    (unless args
      (format *error-output* "Usage: sbcl --script scripts/generate-c-source.lisp <output-file>~%")
      (sb-ext:exit :code 1))
    (let ((path (pathname (first args))))
      (generate-c-source path)
      (format t "Generated C source: ~A~%" path)
      (sb-ext:exit :code 0))))

(main)
